# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/webapp/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00" # UTC
    groups:
      pydantic-ai:
        patterns:
          - "pydantic-ai"
          - "pydantic-ai-examples"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/webapp/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00" # UTC
    groups:
      parcel:
        patterns:
          - "@parcel/*"
          - "parcel"
      jest:
        patterns:
          - "*jest*"
      eslint:
        patterns:
          - "*eslint*"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00" # UTC
    cooldown:
      default-days: 7
